#!/usr/bin/env bash
#
# install.sh — first-time setup for copilot-instructions-starter-kit
#
# Idempotent. Safe to re-run.
#
# What it does:
#   1. Clones the kit to ~/.copilot-kit (skips if already present)
#   2. Creates ~/.copilot/agents/ and ~/.copilot/skills/ (if missing)
#   3. Places ~/.copilot/copilot-instructions.md (symlink on Unix, copy on Windows)
#   4. Writes ~/.copilot-kit/env with COPILOT_CUSTOM_INSTRUCTIONS_DIRS + PATH
#   5. Prints instructions to source the env file from your shell profile
#
# What it does NOT do:
#   - Edit your shell profile (~/.zshrc, ~/.bashrc) — you do this yourself
#   - Auto-activate any agents or skills — you pick via `copilot-kit activate`

set -euo pipefail

REPO_URL="https://github.com/timander/copilot-instructions-starter-kit.git"
KIT_DIR="${KIT_DIR:-$HOME/.copilot-kit}"
COPILOT_DIR="$HOME/.copilot"

note()  { printf "→ %s\n" "$*"; }
warn()  { printf "⚠ %s\n" "$*" >&2; }
ok()    { printf "✓ %s\n" "$*"; }
fail()  { printf "✗ %s\n" "$*" >&2; exit 1; }

# Windows (Git Bash, MSYS, Cygwin) silently deep-copies on `ln -s` by default
# (winsymlinks:deepcopy), which breaks our readlink-based "already linked"
# checks. On Windows we use `cp` directly — explicit and consistent.
is_windows() {
  case "${OSTYPE:-}" in msys*|cygwin*) return 0 ;; esac
  case "$(uname -s 2>/dev/null)" in MINGW*|MSYS*|CYGWIN*) return 0 ;; esac
  return 1
}

already_in_place() {
  local link="$1" target="$2"
  if is_windows; then
    [[ -f "${link}" ]] && cmp -s "${link}" "${target}"
  else
    [[ -L "${link}" && "$(readlink "${link}")" == "${target}" ]]
  fi
}

# --- 1. Clone (or detect existing) -------------------------------------------

if [[ -d "${KIT_DIR}/.git" ]]; then
  ok "kit already cloned at ${KIT_DIR}"
elif [[ -d "$(pwd)/.git" && -f "$(pwd)/copilot-instructions.md" && -d "$(pwd)/agents" ]]; then
  note "running from inside the kit repo; using \$PWD as the kit location"
  KIT_DIR="$(pwd)"
  ok "kit location: ${KIT_DIR}"
else
  note "cloning kit to ${KIT_DIR}"
  command -v git >/dev/null || fail "git not found in PATH"
  git clone --depth 1 "${REPO_URL}" "${KIT_DIR}"
  ok "cloned"
fi

# --- 2. Create ~/.copilot/ dirs ----------------------------------------------

mkdir -p "${COPILOT_DIR}/agents" "${COPILOT_DIR}/skills"
ok "ensured ${COPILOT_DIR}/agents and ${COPILOT_DIR}/skills"

# --- 3. Place copilot-instructions.md ----------------------------------------
# Unix: symlink. Windows: cp (see is_windows comment above).

LINK="${COPILOT_DIR}/copilot-instructions.md"
TARGET="${KIT_DIR}/copilot-instructions.md"

if already_in_place "${LINK}" "${TARGET}"; then
  ok "copilot-instructions.md already in place"
elif [[ -e "${LINK}" ]]; then
  warn "${LINK} exists and differs from the kit's version"
  warn "back it up and re-run, or replace manually:"
  if is_windows; then
    warn "  cp '${TARGET}' '${LINK}'"
  else
    warn "  ln -sf '${TARGET}' '${LINK}'"
  fi
elif is_windows; then
  cp "${TARGET}" "${LINK}"
  ok "copied ${TARGET} → ${LINK}"
  note "Windows: re-run install.sh after 'copilot-kit update' to refresh"
else
  ln -s "${TARGET}" "${LINK}"
  ok "symlinked ${LINK} → ${TARGET}"
fi

# --- 4. Write ~/.copilot-kit/env ---------------------------------------------

ENV_FILE="${KIT_DIR}/env"
cat > "${ENV_FILE}" <<EOF
# Generated by copilot-instructions-starter-kit install.sh
# Source this from your shell profile (~/.zshrc, ~/.bashrc, etc.)

export COPILOT_CUSTOM_INSTRUCTIONS_DIRS="\${COPILOT_CUSTOM_INSTRUCTIONS_DIRS:+\${COPILOT_CUSTOM_INSTRUCTIONS_DIRS},}${KIT_DIR}"

case ":\${PATH}:" in
  *":${KIT_DIR}/bin:"*) : ;;
  *) export PATH="${KIT_DIR}/bin:\${PATH}" ;;
esac
EOF
chmod 644 "${ENV_FILE}"
ok "wrote ${ENV_FILE}"

# Ensure copilot-kit CLI is executable
chmod +x "${KIT_DIR}/bin/copilot-kit" 2>/dev/null || true

# --- 5. Print next steps ------------------------------------------------------

cat <<EOM

──────────────────────────────────────────────────────────────────────
Install complete.

Next steps:

  1. Add this line to your shell profile (e.g. ~/.zshrc or ~/.bashrc):

       source ${ENV_FILE}

  2. Open a new shell (or run \`source ${ENV_FILE}\` in this one).

  3. List what's available:

       copilot-kit list

  4. Activate the agents and skills you want:

       copilot-kit activate diagnose       # diagnose agent
       copilot-kit activate review         # review skill
       copilot-kit activate kit-doctor     # self-audit skill

  5. Verify Copilot CLI sees the kit:

       copilot-kit doctor

──────────────────────────────────────────────────────────────────────
EOM
